version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: radar
      POSTGRES_PASSWORD: radar
      POSTGRES_DB: radar
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: ['5672:5672','15672:15672']